package com.buscatumoto.utils.global

const val MOTOTAG = "MotoTAG"

//BuildTypes
const val DEBUG = "debug"
const val RELEASE = "release"

const val AUTO_SCROLL_TIME_ELLAPSE_MILLIS: Long = 3000

const val MOTO_ID_KEY = "MotoId"

const val LANGUAGE_CA = "ca"
const val LANGUAGE_ES = "es"
const val LANGUAGE_ENG = "en"

const val FADE_IN_ANIMATION_DURATION: Long = 1000
const val FADE_OUT_ANIMATION_DURATION: Long = 1000
const val ALPHA_OPACITY_OPAQUE: Float = 1f
const val ALPHA_OPACITY_TRANSPARENT: Float = 0f

const val EMPTY_SIZE = 0
const val PAGE_START = 0

const val DISPLACEMENT_UNKNOWN = -1.0
const val WEIGHT_UNKNOWN = -1.0
const val POWER_UNKNOWN = -1
const val PRICE_UNKNOWN = -1

const val NOT_DETERMINED_VALUE = "N.D"
const val POWER_ENGLISH = "hp"
const val POWER_ES_CA = "cv"
const val PRICE_ENGLISH = "$"
const val PRICE_ES_CA = "€"

const val DISPLACEMENT_MAGNITUDE = "cc"
const val WEIGHT_MAGNITUDE = "kg"

/**
 * Google Analytics
 */

//item ids
const val ACTIVITY_SEARCH_BTN_SEARCH_ID = "ACTIVITY_SEARCH_BTN_SEARCH"
const val ACTIVITY_SEARCH_EDIT_TEXT_SEARCH_ID = "ACTIVITY_SEARCH_EDIT_TEXT_SEARCH"
const val ACTIVITY_SEARCH_DRAWER_OPEN_ID = "ACTIVITY_SEARCH_DRAWER_OPEN"
const val ACTIVITY_SEARCH_DRAWER_CLOSE_ID = "ACTIVITY_DRAWER_CLOSE"
const val DRAWER_OPTION_LANGUAGE_ID = "DRAWER_OPTION_LANGUAGE"
const val SEARCH_TAB_ID = "SEARCH_TAB_ID"
const val FILTER_TAB_ID = "FILTER_TAB_ID"
const val SEARCH_BRAND_ITEM_ID = "SEARCH_BRAND_ITEM_ID"
const val LANGUAGE_ES_ITEM_ID = "LANGUAGE_ES_ITEM"
const val LANGUAGE_CA_ITEM_ID = "LANGUAGE_CA_ITEM"
const val LANGUAGE_EN_ITEM_ID = "LANGUAGE_EN_ITEM"
const val FILTER_DELETE_BTN_ID = "FILTER_DELETE_BTN"
const val FILTER_BRAND_LIST_EXPAND_ID = "FILTER_BRAND_LIST_EXPAND"
const val FILTER_BRAND_LIST_COLLAPSE_ID = "FILTER_BRAND_LIST_COLLAPSE"
const val FILTER_BRAND_VALUE_SELECTED = "FILTER_BRAND_VALUE_SELECTED"
const val FILTER_TYPE_LIST_EXPAND = "FILTER_TYPE_LIST_EXPAND"
const val FILTER_TYPE_LIST_COLLAPSE = "FILTER_TYPE_LIST_COLLAPSE"
const val FILTER_TYPE_VALUE_SELECTED = "FILTER_TYPE_VALUE_SELECTED"
const val FILTER_PRICE_MIN_LIST_EXPAND = "FILTER_PRICE_MIN_LIST_EXPAND"
const val FILTER_PRICE_MIN_LIST_COLLAPSE = "FILTER_PRICE_MIN_LIST_COLLAPSE"
const val FILTER_PRICE_MIN_VALUE_SELECTED = "FILTER_PRICE_MIN_VALUE_SELECTED"
const val FILTER_PRICE_MAX_LIST_EXPAND = "FILTER_PRICE_MAX_LIST_EXPAND"
const val FILTER_PRICE_MAX_LIST_COLLAPSE = "FILTER_PRICE_MAX_LIST_COLLAPSE"
const val FILTER_PRICE_MAX_VALUE_SELECTED = "FILTER_PRICE_MAX_VALUE_SELECTED"
const val FILTER_POWER_MIN_LIST_EXPAND = "FILTER_POWER_MIN_LIST_EXPAND"
const val FILTER_POWER_MIN_LIST_COLLAPSE = "FILTER_POWER_MIN_LIST_COLLAPSE"
const val FILTER_POWER_MIN_VALUE_SELECTED = "FILTER_POWER_MIN_VALUE_SELECTED"
const val FILTER_POWER_MAX_LIST_EXPAND = "FILTER_POWER_MAX_LIST_EXPAND"
const val FILTER_POWER_MAX_LIST_COLLAPSE = "FILTER_POWER_MAX_LIST_COLLAPSE"
const val FILTER_POWER_MAX_VALUE_SELECTED = "FILTER_POWER_MAX_VALUE_SELECTED"
const val FILTER_DISPLACEMENT_MIN_LIST_EXPAND = "FILTER_DISPLACEMENT_MIN_LIST_EXPAND"
const val FILTER_DISPLACEMENT_MIN_LIST_COLLAPSE = "FILTER_DISPLACEMENT_MIN_LIST_COLLAPSE"
const val FILTER_DISPLACEMENT_MIN_VALUE_SELECTED = "FILTER_DISPLACEMENT_MIN_VALUE_SELECTED"
const val FILTER_DISPLACEMENT_MAX_LIST_EXPAND = "FILTER_DISPLACEMENT_MAX_LIST_EXPAND"
const val FILTER_DISPLACEMENT_MAX_LIST_COLLAPSE = "FILTER_DISPLACEMENT_MAX_LIST_COLLAPSE"
const val FILTER_DISPLACEMENT_MAX_VALUE_SELECTED = "FILTER_DISPLACEMENT_MAX_VALUE_SELECTED"
const val FILTER_WEIGHT_MIN_LIST_EXPAND = "FILTER_WEIGHT_MIN_LIST_EXPAND"
const val FILTER_WEIGHT_MIN_LIST_COLLAPSE = "FILTER_WEIGHT_MIN_LIST_COLLAPSE"
const val FILTER_WEIGHT_MIN_VALUE_SELECTED = "FILTER_WEIGHT_MIN_VALUE_SELECTED"
const val FILTER_WEIGHT_MAX_LIST_EXPAND = "FILTER_WEIGHT_MAX_LIST_EXPAND"
const val FILTER_WEIGHT_MAX_LIST_COLLAPSE = "FILTER_WEIGHT_MAX_LIST_COLLAPSE"
const val FILTER_WEIGHT_MAX_VALUE_SELECTED = "FILTER_WEIGHT_MAX_VALUE_SELECTED"
const val FILTER_YEAR_LIST_EXPAND = "FILTER_YEAR_LIST_EXPAND"
const val FILTER_YEAR_LIST_COLLAPSE = "FILTER_YEAR_LIST_COLLAPSE"
const val FILTER_YEAR_VALUE_SELECTED = "FILTER_YEAR_VALUE_SELECTED"
const val FILTER_LICENSE_LIST_EXPAND = "FILTER_LICENSE_LIST_EXPAND"
const val FILTER_LICENSE_LIST_COLLAPSE = "FILTER_LICENSE_LIST_COLLAPSE"
const val FILTER_LICENSE_VALUE_SELECTED_ID = "FILTER_LICENSE_VALUE_SELECTED"


//Content types
const val DRAWER_CONTENT_TYPE = "MENU"
const val SEARCH_CONTENT_TYPE = "SEARCH"
const val TAB_CONTENT_TYPE = "TABS"
const val LANG_CONTENT_TYPE = "LANGUAGE"
const val FILTER_CONTENT_TYPE = "FILTER"

//Layout item names
const val ACTIVITY_SEARCH_SEARCH_BTN_NAME = "ACTIVITY_SEARCH_BTN_SEARCH"
const val ACTIVITY_SEARCH_EDIT_TEXT_SEARCH_NAME = "ACTIVITY_SEARCH_EDIT_TEXT_SEARCH"
const val ACTIVITY_SEARCH_DRAWER_OPEN_NAME = "ACTIVITY_SEARCH_DRAWER_OPEN"
const val ACTIVITY_SEARCH_DRAWER_CLOSE_NAME = "ACTIVITY_DRAWER_CLOSE"

/**
 * Google Analytics
 */



/**
 * Main Container Fragment
 */

const val SEARCH_FRAGMENT_TAB_POSITION = 0
const val FILTER_FRAGMENT_TAB_POSITION = 1



/**
 * Main Container Fragment
 */
